# Generated by Django 6.0.3 on 2026-03-31 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circunscripciones', to='control_electoral.asientoelectoral')),
            ],
        ),
        migrations.AddField(
            model_name='asientoelectoral',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='control_electoral.municipio'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='control_electoral.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='control_electoral.provincia'),
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('circunscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recintos', to='control_electoral.circunscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('candidato1', models.IntegerField(default=0)),
                ('candidato2', models.IntegerField(default=0)),
                ('candidato3', models.IntegerField(default=0)),
                ('candidato4', models.IntegerField(default=0)),
                ('candidato5', models.IntegerField(default=0)),
                ('votantes_habilitados', models.IntegerField(default=0)),
                ('votos_emitidos', models.IntegerField(default=0)),
                ('votos_validos', models.IntegerField(default=0)),
                ('votos_blancos', models.IntegerField(default=0)),
                ('votos_nulos', models.IntegerField(default=0)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='control_electoral.recinto')),
            ],
        ),
    ]
